In [1]:
import tensorflow as tf

In [2]:
A = [[1,2,3],[4,5,6],[7,8,9],[1,2,3],[4,5,6],[7,8,9]]
x = tf.split(A, num_or_size_splits=3)

In [4]:
with tf.Session() as sess:
    c = sess.run(x)
    for ele in c:
        print(ele)

[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [1 2 3]]
[[4 5 6]
 [7 8 9]]
